interface values {
    billerStreetAddress: string,
    billerCity: string,
    billerPinCode: string,
    billerCountry: string,
    clientName: string,
    clientEmail: string,
    clientStreetAddress: string,
    clientCity: string,
    clientPinCode: string,
    clientCountry: string,
    invoiceDateUnix: Date,
    invoiceDate: Date,
    paymentTerms: string,
    paymentDueDateUnix: Date,
    paymentDueDate: Date,
    productDescription: string,
    invoicePending: number,
    invoiceDraft: number,
    invoiceItemList: [],
    invoiceTotal: number,
}

export const initialValues: values = {
    billerStreetAddress: '',
    billerCity: '',
    billerPinCode: '',
    billerCountry: '',
    clientName: '',
    clientEmail: '',
    clientStreetAddress: '',
    clientCity: '',
    clientPinCode: '',
    clientCountry: '',
    invoiceDateUnix: new Date(),
    invoiceDate: new Date(),
    paymentTerms: '',
    paymentDueDateUnix: new Date(),
    paymentDueDate: new Date(),
    productDescription: '',
    invoicePending: 0,
    invoiceDraft: 0,
    invoiceItemList: [],
    invoiceTotal: 0,
}